// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	goods "github.com/myboran/zshop/app/goods/cmd/api/internal/handler/goods"
	"github.com/myboran/zshop/app/goods/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/goods/list",
				Handler: goods.ListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/goods/:id",
				Handler: goods.GoodsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/goods/v1"),
	)
}
