// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: order.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OrderClient is the client API for Order service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderClient interface {
	AllOrderInfo(ctx context.Context, in *OrderEmpty, opts ...grpc.CallOption) (*AllOrderResp, error)
	AllOrderGoods(ctx context.Context, in *OrderGoodsReq, opts ...grpc.CallOption) (*OrderGoodsResp, error)
	UserOrder(ctx context.Context, in *UserOrderReq, opts ...grpc.CallOption) (*UserOrderResp, error)
}

type orderClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderClient(cc grpc.ClientConnInterface) OrderClient {
	return &orderClient{cc}
}

func (c *orderClient) AllOrderInfo(ctx context.Context, in *OrderEmpty, opts ...grpc.CallOption) (*AllOrderResp, error) {
	out := new(AllOrderResp)
	err := c.cc.Invoke(ctx, "/pb.order/AllOrderInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) AllOrderGoods(ctx context.Context, in *OrderGoodsReq, opts ...grpc.CallOption) (*OrderGoodsResp, error) {
	out := new(OrderGoodsResp)
	err := c.cc.Invoke(ctx, "/pb.order/AllOrderGoods", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) UserOrder(ctx context.Context, in *UserOrderReq, opts ...grpc.CallOption) (*UserOrderResp, error) {
	out := new(UserOrderResp)
	err := c.cc.Invoke(ctx, "/pb.order/UserOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServer is the server API for Order service.
// All implementations must embed UnimplementedOrderServer
// for forward compatibility
type OrderServer interface {
	AllOrderInfo(context.Context, *OrderEmpty) (*AllOrderResp, error)
	AllOrderGoods(context.Context, *OrderGoodsReq) (*OrderGoodsResp, error)
	UserOrder(context.Context, *UserOrderReq) (*UserOrderResp, error)
	mustEmbedUnimplementedOrderServer()
}

// UnimplementedOrderServer must be embedded to have forward compatible implementations.
type UnimplementedOrderServer struct {
}

func (UnimplementedOrderServer) AllOrderInfo(context.Context, *OrderEmpty) (*AllOrderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllOrderInfo not implemented")
}
func (UnimplementedOrderServer) AllOrderGoods(context.Context, *OrderGoodsReq) (*OrderGoodsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllOrderGoods not implemented")
}
func (UnimplementedOrderServer) UserOrder(context.Context, *UserOrderReq) (*UserOrderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserOrder not implemented")
}
func (UnimplementedOrderServer) mustEmbedUnimplementedOrderServer() {}

// UnsafeOrderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderServer will
// result in compilation errors.
type UnsafeOrderServer interface {
	mustEmbedUnimplementedOrderServer()
}

func RegisterOrderServer(s grpc.ServiceRegistrar, srv OrderServer) {
	s.RegisterService(&Order_ServiceDesc, srv)
}

func _Order_AllOrderInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).AllOrderInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.order/AllOrderInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).AllOrderInfo(ctx, req.(*OrderEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_AllOrderGoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderGoodsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).AllOrderGoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.order/AllOrderGoods",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).AllOrderGoods(ctx, req.(*OrderGoodsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_UserOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).UserOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.order/UserOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).UserOrder(ctx, req.(*UserOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Order_ServiceDesc is the grpc.ServiceDesc for Order service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Order_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.order",
	HandlerType: (*OrderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AllOrderInfo",
			Handler:    _Order_AllOrderInfo_Handler,
		},
		{
			MethodName: "AllOrderGoods",
			Handler:    _Order_AllOrderGoods_Handler,
		},
		{
			MethodName: "UserOrder",
			Handler:    _Order_UserOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
