// Code generated by goctl. DO NOT EDIT.
// Source: inventory.proto

package inventory

import (
	"context"

	"github.com/myboran/zshop/app/inventory/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	InventoryDetailReq  = pb.InventoryDetailReq
	InventoryDetailResp = pb.InventoryDetailResp
	InventoryEmpty      = pb.InventoryEmpty

	Inventory interface {
		InventoryDetail(ctx context.Context, in *InventoryDetailReq, opts ...grpc.CallOption) (*InventoryDetailResp, error)
	}

	defaultInventory struct {
		cli zrpc.Client
	}
)

func NewInventory(cli zrpc.Client) Inventory {
	return &defaultInventory{
		cli: cli,
	}
}

func (m *defaultInventory) InventoryDetail(ctx context.Context, in *InventoryDetailReq, opts ...grpc.CallOption) (*InventoryDetailResp, error) {
	client := pb.NewInventoryClient(m.cli.Conn())
	return client.InventoryDetail(ctx, in, opts...)
}
