// Code generated by goctl. DO NOT EDIT.
// Source: order.proto

package server

import (
	"context"

	"github.com/myboran/zshop/app/order/cmd/rpc/internal/logic"
	"github.com/myboran/zshop/app/order/cmd/rpc/internal/svc"
	"github.com/myboran/zshop/app/order/cmd/rpc/pb"
)

type OrderServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedOrderServer
}

func NewOrderServer(svcCtx *svc.ServiceContext) *OrderServer {
	return &OrderServer{
		svcCtx: svcCtx,
	}
}

func (s *OrderServer) AllOrderInfo(ctx context.Context, in *pb.OrderEmpty) (*pb.AllOrderResp, error) {
	l := logic.NewAllOrderInfoLogic(ctx, s.svcCtx)
	return l.AllOrderInfo(in)
}

func (s *OrderServer) AllOrderGoods(ctx context.Context, in *pb.OrderGoodsReq) (*pb.OrderGoodsResp, error) {
	l := logic.NewAllOrderGoodsLogic(ctx, s.svcCtx)
	return l.AllOrderGoods(in)
}

func (s *OrderServer) UserOrder(ctx context.Context, in *pb.UserOrderReq) (*pb.UserOrderResp, error) {
	l := logic.NewUserOrderLogic(ctx, s.svcCtx)
	return l.UserOrder(in)
}
