// Code generated by goctl. DO NOT EDIT.
package types

type Order struct {
	Id      int64  `json:"id"`
	User    int64  `json:"user"`
	OrderSn string `json:"order_sn"`
	Status  string `json:"status"`
}

type UserOrderReq struct {
	UserId int64 `path:"userId"`
}

type OrderResp struct {
	Orders []Order `json:"orders"`
}

type OrderGoods struct {
	Id        int64   `json:"id"`
	OrderSn   string  `json:"order_sn"`
	Goods     int64   `json:"goods"`
	GoodsName string  `json:"goodsName"`
	Price     float64 `json:"price"`
	Nums      int64   `json:"nums"`
}

type OrderGoodsReq struct {
	OrderSn string `path:"order_sn"`
}

type OrderGoodsResp struct {
	Goods []OrderGoods `json:"goods"`
}
