// Code generated by goctl. DO NOT EDIT.
// Source: inventory.proto

package server

import (
	"context"

	"github.com/myboran/zshop/app/inventory/cmd/rpc/internal/logic"
	"github.com/myboran/zshop/app/inventory/cmd/rpc/internal/svc"
	"github.com/myboran/zshop/app/inventory/cmd/rpc/pb"
)

type InventoryServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedInventoryServer
}

func NewInventoryServer(svcCtx *svc.ServiceContext) *InventoryServer {
	return &InventoryServer{
		svcCtx: svcCtx,
	}
}

func (s *InventoryServer) InventoryDetail(ctx context.Context, in *pb.InventoryDetailReq) (*pb.InventoryDetailResp, error) {
	l := logic.NewInventoryDetailLogic(ctx, s.svcCtx)
	return l.InventoryDetail(in)
}
