// Code generated by goctl. DO NOT EDIT.

package inventoryModel

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	inventoryFieldNames          = builder.RawFieldNames(&Inventory{})
	inventoryRows                = strings.Join(inventoryFieldNames, ",")
	inventoryRowsExpectAutoSet   = strings.Join(stringx.Remove(inventoryFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	inventoryRowsWithPlaceHolder = strings.Join(stringx.Remove(inventoryFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	inventoryModel interface {
		Insert(ctx context.Context, data *Inventory) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Inventory, error)
		FindOneByGoods(ctx context.Context, goods int64) (*Inventory, error)
		Update(ctx context.Context, data *Inventory) error
		Delete(ctx context.Context, id int64) error
	}

	defaultInventoryModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Inventory struct {
		Id     int64 `db:"id"`
		Goods  int64 `db:"goods"`  // 商品id
		Stocks int64 `db:"stocks"` // 库存数量
		Freeze int64 `db:"freeze"` // 冻结数量
	}
)

func newInventoryModel(conn sqlx.SqlConn) *defaultInventoryModel {
	return &defaultInventoryModel{
		conn:  conn,
		table: "`inventory`",
	}
}

func (m *defaultInventoryModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultInventoryModel) FindOne(ctx context.Context, id int64) (*Inventory, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", inventoryRows, m.table)
	var resp Inventory
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultInventoryModel) FindOneByGoods(ctx context.Context, goods int64) (*Inventory, error) {
	var resp Inventory
	query := fmt.Sprintf("select %s from %s where `goods` = ? limit 1", inventoryRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, goods)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultInventoryModel) Insert(ctx context.Context, data *Inventory) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, inventoryRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Goods, data.Stocks, data.Freeze)
	return ret, err
}

func (m *defaultInventoryModel) Update(ctx context.Context, newData *Inventory) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, inventoryRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Goods, newData.Stocks, newData.Freeze, newData.Id)
	return err
}

func (m *defaultInventoryModel) tableName() string {
	return m.table
}
