// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	order "github.com/myboran/zshop/app/order/cmd/api/internal/handler/order"
	"github.com/myboran/zshop/app/order/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/order/all",
				Handler: order.AllOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/order/user/:userId",
				Handler: order.UserOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/order/goods/:order_sn",
				Handler: order.OrderGoodsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/order/v1"),
	)
}
